version: '3.8'

services:
  postgres:
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - movies

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      PORT: ${PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: postgres # the name of the service defined above
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - movies

networks:
 movies:
    driver: bridge

