"""create_directors_table

Revision ID: 32b72759cde6
Revises: c04c9251a907
Create Date: 2023-09-05 17:21:46.242108

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '32b72759cde6'
down_revision = 'c04c9251a907'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directors',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('full_name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_directors_full_name'), 'directors', ['full_name'], unique=True)
    op.create_index(op.f('ix_directors_id'), 'directors', ['id'], unique=False)
    op.add_column('movies', sa.Column('director_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'movies', 'directors', ['director_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.drop_column('movies', 'director_id')
    op.drop_index(op.f('ix_directors_id'), table_name='directors')
    op.drop_index(op.f('ix_directors_full_name'), table_name='directors')
    op.drop_table('directors')
    # ### end Alembic commands ###
