"""create movies table

Revision ID: d99d13b94df7
Revises: 
Create Date: 2023-04-12 17:00:12.601820

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd99d13b94df7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('overview', sa.String(), nullable=True),
                    sa.Column('year', sa.Integer(), nullable=True),
                    sa.Column('rating', sa.Float(), nullable=True),
                    sa.Column('category', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
