name: Continuous Integration and Deployment (master)

on:
  push:
    branches:
      - master

jobs:
  CI:
    name: Continuos Integration
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.6'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Make the environment file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PORT: ${{secrets.PORT}}
          envkey_JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
          envkey_DATABASE_HOST: ${{secrets.DATABASE_HOST}}
          envkey_DATABASE_PORT: ${{secrets.DATABASE_PORT}}
          envkey_DATABASE_NAME: ${{secrets.DATABASE_NAME}}
          envkey_DATABASE_USER: ${{secrets.DATABASE_USER}}
          envkey_DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          fail_on_empty: true
      - name: Run migrations
        run: alembic upgrade head
      - name: Run tests
        run: pytest
  CD:
    name: Continuos Deployment
    runs-on: ubuntu-latest
    needs: CI
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Execute remote commands via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SSH_HOST }}
          username: ${{ secrets.AWS_SSH_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd movies
            git pull origin master
            source venv/bin/activate
            pip install -r requirements.txt
            /home/ubuntu/.nvm/versions/node/v20.3.0/bin/node /home/ubuntu/.nvm/versions/node/v20.3.0/bin/pm2 reload 1
